"""
Django settings for FruitSortingSystem project.

Originally generated by Django and maintained for Django 5.2 LTS.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Local development settings live at the repository root. Existing process
# environment variables take precedence over values from this ignored file.
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-key-change-before-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'fruit_app',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FruitSortingSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [],
        },
    },
]

WSGI_APPLICATION = 'FruitSortingSystem.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 定義媒體檔案的實體儲存路徑與網址路徑
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 百香果資料蒐集輸出根目錄。
DATASET_ROOT = BASE_DIR / 'dataset'

# Automatic inspection stays separate from the manually labelled Dataset.
def _project_path(environment_name, default):
    configured = Path(os.environ.get(environment_name, default)).expanduser()
    return configured if configured.is_absolute() else BASE_DIR.parent / configured


MODEL_REPOSITORY_ROOT = _project_path(
    'MODEL_REPOSITORY_ROOT',
    BASE_DIR.parent / 'external' / 'ps-quality-detection-system',
)
DETECTION_OUTPUT_ROOT = _project_path(
    'DETECTION_OUTPUT_ROOT',
    BASE_DIR / 'detection_results',
)
DETECTION_MODEL_PATHS = {
    'roi': str(_project_path(
        'DETECTION_ROI_MODEL',
        str(MODEL_REPOSITORY_ROOT / 'models' / 'ROI_crop.pt'),
    )),
    'color': str(_project_path(
        'DETECTION_COLOR_MODEL',
        str(MODEL_REPOSITORY_ROOT / 'models' / 'v2_color.pt'),
    )),
    'wrinkle': str(_project_path(
        'DETECTION_WRINKLE_MODEL',
        str(MODEL_REPOSITORY_ROOT / 'models' / 'v2_wrinkle.pt'),
    )),
    'defect': str(_project_path(
        'DETECTION_DEFECT_MODEL',
        str(MODEL_REPOSITORY_ROOT / 'models' / 'v22_defect.pt'),
    )),
}
DETECTION_MODEL_OPTIONS = {
    'roi': {'confidence': 0.25, 'imgsz': 640},
    'color': {'imgsz': 320},
    'wrinkle': {'imgsz': 320},
    'defect': {'imgsz': 1024},
}

# Dashboard 停穩時間的單一持久化設定。此檔案不屬於 dataset，避免與照片資料混在一起。
RUNTIME_CONFIG_ROOT = BASE_DIR / 'runtime_config'
CAPTURE_TIMING_CONFIG_PATH = RUNTIME_CONFIG_ROOT / 'capture_timing.json'
MOTOR_COMMAND_SEQUENCE_PATH = RUNTIME_CONFIG_ROOT / 'motor_command_sequence.json'
